apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-chat-deployment
  labels:
    app: chat
spec:
  replicas: 3
  selector:
    matchLabels:
        app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: profile
        image: us.gcr.io/gcp-docker-kubernetes-363806/clouduser/groupchat:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: MYSQL_DB_HOST
        - name: MYSQL_DB_USER
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: MYSQL_DB_USER
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: MYSQL_DB_PASSWORD
        - name: MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: MYSQL_DB_PORT

        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: SPRING_REDIS_HOST
        - name:  SPRING_REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key:  SPRING_REDIS_PASSWORD
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: SPRING_REDIS_PORT
        - name: RAW_TOPIC_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: RAW_TOPIC_MESSAGE
        - name: LIST_OF_PROFILE_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: spring-chat-config
              key: LIST_OF_PROFILE_ENDPOINTS



---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-chat-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
