apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: profile
spec:
  replicas: 3
  selector:
    matchLabels:
        app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: us.gcr.io/gcp-docker-kubernetes-363806/clouduser/task3:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-profile-config
              key: MYSQL_DB_HOST
        - name: MYSQL_DB_USER
          valueFrom:
            configMapKeyRef:
              name: spring-profile-config
              key: MYSQL_DB_USER
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: spring-profile-config
              key: MYSQL_DB_PASSWORD
        - name: MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-profile-config
              key: MYSQL_DB_PORT



             
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: profile-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-profile-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
