apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: login
spec:
  replicas: 3
  selector:
    matchLabels:
        app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: profile
        image: us.gcr.io/gcp-docker-kubernetes-363806/clouduser/login:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-login-config
              key: MYSQL_DB_HOST
        - name: MYSQL_DB_USER
          valueFrom:
            configMapKeyRef:
              name: spring-login-config
              key: MYSQL_DB_USER
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: spring-login-config
              key: MYSQL_DB_PASSWORD
        - name: MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-login-config
              key: MYSQL_DB_PORT

        - name: CHAT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: spring-login-config
              key: CHAT_ENDPOINT



---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
